In [55]:
import talib as ta
import numpy as np
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # 한 실행칸에 프린트 여러개 해도 다 출력시키도록 하는 코드.

In [56]:
raw_data = pd.read_csv('./kospi_1분봉_201910_202010.csv')

In [57]:
def data_make_function(open_p, high_p, low_p, close_p ,volume):
  e_f = pd.DataFrame()
  #BBANDS - Bollinger Bands
  
  upperband, middleband, lowerband = ta.BBANDS(close_p, timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
  e_f['BBANDS_upperband'] = upperband
  e_f['BBANDS_middleband'] = middleband
  e_f['BBANDS_lowerband'] = lowerband
  
  #DEMA - Double Exponential Moving Average
  e_f['DEMA'] = ta.DEMA(close_p, timeperiod=30)
  
  #EMA - Exponential Moving Average
  e_f['EMA'] = ta.EMA(close_p, timeperiod=30)
  
  #HT_TRENDLINE - Hilbert Transform - Instantaneous Trendline
  e_f['HT_TRENDLINE'] = ta.HT_TRENDLINE(close_p)
  
  
  #KAMA - Kaufman Adaptive Moving Average
  e_f['KAMA'] = ta.KAMA(close_p, timeperiod=30)
  
  #MA - Moving average
  e_f['MA'] = ta.MA(close_p, timeperiod=30, matype=0)
  
  #MAMA - MESA Adaptive Moving Average
 # mama, fama = ta.MAMA(close_p, fastlimit=0, slowlimit=0)
  
  #e_f['mama'] = mama
  #e_f['fama'] = fama
  
  #MAVP - Moving average with variable period
 # e_f['MAVP'] = ta.MAVP(close_p, periods, minperiod=2, maxperiod=30, matype=0)
  
  #MIDPOINT - MidPoint over period
  e_f['MIDPOINT'] = ta.MIDPOINT(close_p, timeperiod=14)
  
  #MIDPRICE - Midpoint Price over period
  e_f['MIDPRICE'] = ta.MIDPRICE(high_p, low_p, timeperiod=14)
  
  #SAR - Parabolic SAR
  e_f['SAR'] = ta.SAR(high_p, low_p, acceleration=0, maximum=0)
  
  #SAREXT - Parabolic SAR - Extended
  e_f['SAREXT'] = ta.SAREXT(high_p, low_p, startvalue=0, offsetonreverse=0, accelerationinitlong=0, accelerationlong=0, accelerationmaxlong=0, accelerationinitshort=0, accelerationshort=0, accelerationmaxshort=0)
  
  #SMA - Simple Moving Average
  e_f['SMA'] = ta.SMA(close_p, timeperiod=30)
  
  #T3 - Triple Exponential Moving Average (T3)
  e_f['T3'] = ta.T3(close_p, timeperiod=5, vfactor=0)
  
  #TEMA - Triple Exponential Moving Average
  e_f['TEMA'] = ta.TEMA(close_p, timeperiod=30)
  
  #TRIMA - Triangular Moving Average
  e_f['TRIMA'] = ta.TRIMA(close_p, timeperiod=30)
  
  #WMA - Weighted Moving Average
  e_f['WMA'] = ta.WMA(close_p, timeperiod=30)
  
  #- Momentum Indicator Functions
  
  #ADX - Average Directional Movement Index
  e_f['ADX'] = ta.ADX(high_p, low_p, close_p, timeperiod=14)
  
  #ADXR - Average Directional Movement Index Rating
  e_f['ADXR'] = ta.ADXR(high_p, low_p, close_p, timeperiod=14)
  
  #APO - Absolute Price Oscillator
  e_f['APO'] = ta.APO(close_p, fastperiod=12, slowperiod=26, matype=0)
  
  #AROON - Aroon
#  aroondown, aroonup = ta.AROON(high_p, low_p, timeperiod=14)
  
 # e_f['aroondown'] = ta.aroondown
  #e_f['aroonup'] = ta.aroonup
  
  #AROONOSC - Aroon Oscillator
  #e_f['AROONOSC'] = ta.AROONOSC(high_p, low_p, timeperiod=14)
  
  #BOP - Balance Of Power
  e_f['BOP'] = ta.BOP(open_p, high_p, low_p, close_p)
  
  #CCI - Commodity Channel Index
  e_f['CCI'] = ta.CCI(high_p, low_p, close_p, timeperiod=14)
  
  #CMO - Chande Momentum Oscillator
  e_f['CMO'] = ta.CMO(close_p, timeperiod=14)
  
  #DX - Directional Movement Index
  e_f['DX'] = ta.DX(high_p, low_p, close_p, timeperiod=14)
  
  #MACD - Moving Average Convergence/Divergence
  macd, macdsignal, macdhist = ta.MACD(close_p, fastperiod=12, slowperiod=26, signalperiod=9)
  
  e_f['macd_MACD'] = macd 
  e_f['macdsignal_MACD'] = macdsignal 
  e_f['macdhist_MACD'] = macdhist 
  
  
  #MACDEXT - MACD with controllable MA type
  macd, macdsignal, macdhist = ta.MACDEXT(close_p, fastperiod=12, fastmatype=0, slowperiod=26, slowmatype=0, signalperiod=9, signalmatype=0)
  e_f['macd_MACDEXT'] = macd 
  e_f['macdsignal_MACDEXT'] = macdsignal 
  e_f['macdhist_MACDEXT'] = macdhist 
  
  
  #MACDFIX - Moving Average Convergence/Divergence Fix 12/26
  macd, macdsignal, macdhist = ta.MACDFIX(close_p, signalperiod=9)
  e_f['macd_MACDFIX'] = macd 
  e_f['macdsignal_MACDFIX'] = macdsignal 
  e_f['macdhist_MACDFIX'] = macdhist 
  
  
  
  #MFI - Money Flow Index
  e_f['MFI'] = ta.MFI(high_p, low_p, close_p, volume, timeperiod=14)
  
  #MINUS_DI - Minus Directional Indicator
  e_f['MINUS_DI'] = ta.MINUS_DI(high_p, low_p, close_p, timeperiod=14)
  
  #MINUS_DM - Minus Directional Movement
  e_f['MINUS_DM'] = ta.MINUS_DM(high_p, low_p, timeperiod=14)
  
  #MOM - Momentum
  e_f['MOM'] = ta.MOM(close_p, timeperiod=10)
  
  #PLUS_DI - Plus Directional Indicator
  e_f['PLUS_DI'] = ta.PLUS_DI(high_p, low_p, close_p, timeperiod=14)
  
  #PLUS_DM - Plus Directional Movement
  e_f['PLUS_DM'] = ta.PLUS_DM(high_p, low_p, timeperiod=14)
  
  #PPO - Percentage Price Oscillator
  e_f['PPO'] = ta.PPO(close_p, fastperiod=12, slowperiod=26, matype=0)
  
  #ROC - Rate of change : ((price/prevPrice)-1)*100
  e_f['ROC'] = ta.ROC(close_p, timeperiod=10)
  
  #ROCP - Rate of change Percentage: (price-prevPrice)/prevPrice
  e_f['ROCP'] = ta.ROCP(close_p, timeperiod=10)
  
  #ROCR - Rate of change ratio: (price/prevPrice)
  e_f['ROCR'] = ta.ROCR(close_p, timeperiod=10)
  
  #ROCR100 - Rate of change ratio 100 scale: (price/prevPrice)*100
  e_f['ROCR100'] = ta.ROCR100(close_p, timeperiod=10)
  
  #RSI - Relative Strength Index
  e_f['RSI'] = ta.RSI(close_p, timeperiod=14)
  
  #STOCH - Stochastic
  slowk, slowd = ta.STOCH(high_p, low_p, close_p, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
  e_f['slowk'] = slowk
  e_f['slowd'] = slowd
  
  #STOCHF - Stochastic Fast
  fastk, fastd = ta.STOCHF(high_p, low_p, close_p, fastk_period=5, fastd_period=3, fastd_matype=0)
  e_f['fastk_STOCHF'] = fastk
  e_f['fastd_STOCHF'] = fastd
  
  #STOCHRSI - Stochastic Relative Strength Index
  fastk, fastd = ta.STOCHRSI(close_p, timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)
  e_f['slowk_STOCHRSI'] = slowk
  e_f['slowd_STOCHRSI'] = slowd
  
  #TRIX - 1-day Rate-Of-Change (ROC) of a Triple Smooth EMA
  e_f['TRIX'] = ta.TRIX(close_p, timeperiod=30)
  
  #ULTOSC - Ultimate Oscillator
  e_f['ULTOSC'] = ta.ULTOSC(high_p, low_p, close_p, timeperiod1=7, timeperiod2=14, timeperiod3=28)
  
  #WILLR - Williams' %R
  e_f['WILLR'] = ta.WILLR(high_p, low_p, close_p, timeperiod=14)
  
  #- Volume Indicator Functions
  
  #AD - Chaikin A/D Line
  e_f['AD'] = ta.AD(high_p, low_p, close_p, volume)
  
  #ADOSC - Chaikin A/D Oscillator
  e_f['ADOSC'] = ta.ADOSC(high_p, low_p, close_p, volume, fastperiod=3, slowperiod=10)
  
  #OBV - On Balance Volume
  e_f['OBV'] = ta.OBV(close_p, volume)
  
  #- Volatility Indicator Functions
  
  #ATR - Average True Range
  e_f['ATR'] = ta.ATR(high_p, low_p, close_p, timeperiod=14)
  
  #NATR - Normalized Average True Range
  e_f['NATR'] = ta.NATR(high_p, low_p, close_p, timeperiod=14)
  
  #TRANGE - True Range
  e_f['TRANGE'] = ta.TRANGE(high_p, low_p, close_p)
  
  #- Price Transform Functions

  #AVGPRICE - Average Price
  e_f['AVGPRICE'] = ta.AVGPRICE(open_p, high_p, low_p, close_p)
  
  #MEDPRICE - Median Price
  e_f['MEDPRICE'] = ta.MEDPRICE(high_p, low_p)
  
  #TYPPRICE - Typical Price
  e_f['MEDPRICE'] = ta.TYPPRICE(high_p, low_p, close_p)
  
  #WCLPRICE - Weighted close_p Price
  e_f['WCLPRICE'] = ta.WCLPRICE(high_p, low_p, close_p)
  
  #- Cycle Indicator Functions
  
  #HT_DCPERIOD - Hilbert Transform - Dominant Cycle Period
  e_f['HT_DCPERIOD'] = ta.HT_DCPERIOD(close_p)
  
  #HT_DCPHASE - Hilbert Transform - Dominant Cycle Phase
  e_f['HT_DCPHASE'] = ta.HT_DCPHASE(close_p)
  
  #HT_PHASOR - Hilbert Transform - Phasor Components
 # inphase, quadrature = ta.HT_PHASOR(close_p)
  
  #e_f['inphase'] = ta.inphase
  #e_f['quadrature'] = ta.quadrature
  
  #HT_SINE - Hilbert Transform - SineWave
#  sine, leadsine = ta.HT_SINE(close_p)
 # e_f['sine'] = inphase
  #e_f['leadsine'] = quadrature
  
  #HT_TRENDMODE - Hilbert Transform - Trend vs Cycle Mode
  integer = ta.HT_TRENDMODE(close_p)
  e_f['HT_TRENDMODE'] = integer
  
  #- Pattern Recognition Functions
  # CDL2CROWS - Two Crows
  e_f['CDL2CROWS'] = ta.CDL2CROWS(open_p, high_p, low_p, close_p)
  
  # CDL3BLACKCROWS - Three Black Crows
  e_f['CDL3BLACKCROWS'] = ta.CDL3BLACKCROWS(open_p, high_p, low_p, close_p)
  
  # CDL3INSIDE - Three Inside Up/Down
  e_f['CDL3INSIDE'] = ta.CDL3INSIDE(open_p, high_p, low_p, close_p)
  
  # CDL3LINESTRIKE - Three-Line Strike
  e_f['CDL3LINESTRIKE'] = ta.CDL3LINESTRIKE(open_p, high_p, low_p, close_p)
  
  # CDL3OUTSIDE - Three Outside Up/Down
  e_f['CDL3OUTSIDE'] = ta.CDL3OUTSIDE(open_p, high_p, low_p, close_p)
  
  # CDL3STARSINSOUTH - Three Stars In The South
  e_f['CDL3STARSINSOUTH'] = ta.CDL3STARSINSOUTH(open_p, high_p, low_p, close_p)
  
  # CDL3WHITESOLDIERS - Three Advancing White Soldiers
  e_f['CDL3WHITESOLDIERS'] = ta.CDL3WHITESOLDIERS(open_p, high_p, low_p, close_p)
  
  # CDLABANDONEDBABY - Abandoned Baby
  e_f['CDLABANDONEDBABY'] = ta.CDLABANDONEDBABY(open_p, high_p, low_p, close_p, penetration=0)
  
  # CDLADVANCEBLOCK - Advance Block
  e_f['CDLADVANCEBLOCK'] = ta.CDLADVANCEBLOCK(open_p, high_p, low_p, close_p)
  
  # CDLBELTHOLD - Belt-hold
  e_f['CDLBELTHOLD'] = ta.CDLBELTHOLD(open_p, high_p, low_p, close_p)
  
  # CDLBREAKAWAY - Breakaway
  e_f['CDLBREAKAWAY'] = ta.CDLBREAKAWAY(open_p, high_p, low_p, close_p)
  
  # CDLCLOSINGMARUBOZU - Closing Marubozu
  e_f['CDLCLOSINGMARUBOZU'] = ta.CDLCLOSINGMARUBOZU(open_p, high_p, low_p, close_p)
  
  # CDLCONCEALBABYSWALL - Concealing Baby Swallow
  e_f['CDLCONCEALBABYSWALL'] = ta.CDLCONCEALBABYSWALL(open_p, high_p, low_p, close_p)
  
  # CDLCOUNTERATTACK - Counterattack
  e_f['CDLCOUNTERATTACK'] = ta.CDLCOUNTERATTACK(open_p, high_p, low_p, close_p)
  
  # CDLDARKCLOUDCOVER - Dark Cloud Cover
  e_f['CDLDARKCLOUDCOVER'] = ta.CDLDARKCLOUDCOVER(open_p, high_p, low_p, close_p, penetration=0)
  
  # CDLDOJI - Doji
  e_f['CDLDOJI'] = ta.CDLDOJI(open_p, high_p, low_p, close_p)
  
  # CDLDOJISTAR - Doji Star
  e_f['CDLDOJISTAR'] = ta.CDLDOJISTAR(open_p, high_p, low_p, close_p)
  
  # CDLDRAGONFLYDOJI - Dragonfly Doji
  e_f['CDLDRAGONFLYDOJI'] = ta.CDLDRAGONFLYDOJI(open_p, high_p, low_p, close_p)
  
  # CDLENGULFING - Engulfing Pattern
  e_f['CDLENGULFING'] = ta.CDLENGULFING(open_p, high_p, low_p, close_p)
  
  # CDLEVENINGDOJISTAR - Evening Doji Star
  e_f['CDLEVENINGDOJISTAR'] = ta.CDLEVENINGDOJISTAR(open_p, high_p, low_p, close_p, penetration=0)
  # CDLEVENINGSTAR - Evening Star
  e_f['CDLEVENINGSTAR'] = ta.CDLEVENINGSTAR(open_p, high_p, low_p, close_p, penetration=0)
  
  # CDLGAPSIDESIDEWHITE - Up/Down-gap side-by-side white lines
  e_f['CDLGAPSIDESIDEWHITE'] = ta.CDLGAPSIDESIDEWHITE(open_p, high_p, low_p, close_p)
  
  # CDLGRAVESTONEDOJI - Gravestone Doji
  e_f['CDLGRAVESTONEDOJI'] = ta.CDLGRAVESTONEDOJI(open_p, high_p, low_p, close_p)
  
  # CDLHAMMER - Hammer
  e_f['CDLHAMMER'] = ta.CDLHAMMER(open_p, high_p, low_p, close_p)
  
  # CDLHANGINGMAN - Hanging Man
  e_f['CDLHANGINGMAN'] = ta.CDLHANGINGMAN(open_p, high_p, low_p, close_p)
  
  # CDLHARAMI - Harami Pattern
  e_f['CDLHARAMI'] = ta.CDLHARAMI(open_p, high_p, low_p, close_p)
  
  # CDLHARAMICROSS - Harami Cross Pattern
  e_f['CDLHARAMICROSS'] = ta.CDLHARAMICROSS(open_p, high_p, low_p, close_p)
  
  # CDLhigh_pWAVE - high_p-Wave Candle
  #e_f['CDLhigh_pWAVE'] = ta.CDLhigh_pWAVE(open_p, high_p, low_p, close_p)
  
  # CDLHIKKAKE - Hikkake Pattern
  e_f['CDLHIKKAKE'] = ta.CDLHIKKAKE(open_p, high_p, low_p, close_p)
  
  # CDLHIKKAKEMOD - Modified Hikkake Pattern
  e_f['CDLHIKKAKEMOD'] = ta.CDLHIKKAKEMOD(open_p, high_p, low_p, close_p)
  
  # CDLHOMINGPIGEON - Homing Pigeon
  e_f['CDLHOMINGPIGEON'] = ta.CDLHOMINGPIGEON(open_p, high_p, low_p, close_p)
  
  # CDLIDENTICAL3CROWS - Identical Three Crows
  e_f['CDLIDENTICAL3CROWS'] = ta.CDLIDENTICAL3CROWS(open_p, high_p, low_p, close_p)
  
  # CDLINNECK - In-Neck Pattern
  e_f['CDLINNECK'] = ta.CDLINNECK(open_p, high_p, low_p, close_p)
  
  #CDLINVERTEDHAMMER - Inverted Hammer
  e_f['CDLINVERTEDHAMMER'] = ta.CDLINVERTEDHAMMER(open_p, high_p, low_p, close_p)
  
  #CDLKICKING - Kicking
  e_f['CDLKICKING'] = ta.CDLKICKING(open_p, high_p, low_p, close_p)
  
  #CDLKICKINGBYLENGTH - Kicking - bull/bear determined by the longer marubozu
  e_f['CDLKICKINGBYLENGTH'] = ta.CDLKICKINGBYLENGTH(open_p, high_p, low_p, close_p)
  
  #CDLLADDERBOTTOM - Ladder Bottom
  e_f['CDLLADDERBOTTOM'] = ta.CDLLADDERBOTTOM(open_p, high_p, low_p, close_p)
  
  #CDLLONGLEGGEDDOJI - Long Legged Doji
  e_f['CDLLONGLEGGEDDOJI'] = ta.CDLLONGLEGGEDDOJI(open_p, high_p, low_p, close_p)
  
  #CDLLONGLINE - Long Line Candle
  e_f['CDLLONGLINE'] = ta.CDLLONGLINE(open_p, high_p, low_p, close_p)
  
  #CDLMARUBOZU - Marubozu
  e_f['CDLMARUBOZU'] = ta.CDLMARUBOZU(open_p, high_p, low_p, close_p)
  
  #CDLMATCHINGLOW - Matching Low
  e_f['CDLMATCHINGLOW'] = ta.CDLMATCHINGLOW(open_p, high_p, low_p, close_p)
  
  #CDLMATHOLD - Mat Hold
  e_f['CDLMATHOLD'] = ta.CDLMATHOLD(open_p, high_p, low_p, close_p, penetration=0)
  
  #CDLMORNINGDOJISTAR - Morning Doji Star
  e_f['CDLMORNINGDOJISTAR'] = ta.CDLMORNINGDOJISTAR(open_p, high_p, low_p, close_p, penetration=0)
  
  #CDLMORNINGSTAR - Morning Star
  e_f['CDLMORNINGSTAR'] = ta.CDLMORNINGSTAR(open_p, high_p, low_p, close_p, penetration=0)
  
  #CDLONNECK - On-Neck Pattern
  e_f['CDLONNECK'] = ta.CDLONNECK(open_p, high_p, low_p, close_p)
  
  #CDLPIERCING - Piercing Pattern
  e_f['CDLPIERCING'] = ta.CDLPIERCING(open_p, high_p, low_p, close_p)
  
  #CDLRICKSHAWMAN - Rickshaw Man
  e_f['CDLRICKSHAWMAN'] = ta.CDLRICKSHAWMAN(open_p, high_p, low_p, close_p)
  
  #CDLRISEFALL3METHODS - Rising/Falling Three Methods
  e_f['CDLRISEFALL3METHODS'] = ta.CDLRISEFALL3METHODS(open_p, high_p, low_p, close_p)
  
  #CDLSEPARATINGLINES - Separating Lines
  e_f['CDLSEPARATINGLINES'] = ta.CDLSEPARATINGLINES(open_p, high_p, low_p, close_p)
  
  #CDLSHOOTINGSTAR - Shooting Star
  e_f['CDLSHOOTINGSTAR'] = ta.CDLSHOOTINGSTAR(open_p, high_p, low_p, close_p)
  
  #CDLSHORTLINE - Short Line Candle
  e_f['CDLSHORTLINE'] = ta.CDLSHORTLINE(open_p, high_p, low_p, close_p)
  
  #CDLSPINNINGTOP - Spinning Top
  e_f['CDLSPINNINGTOP'] = ta.CDLSPINNINGTOP(open_p, high_p, low_p, close_p)
  
  #CDLSTALLEDPATTERN - Stalled Pattern
  e_f['CDLSTALLEDPATTERN'] = ta.CDLSTALLEDPATTERN(open_p, high_p, low_p, close_p)
  
  #CDLSTICKSANDWICH - Stick Sandwich
  e_f['CDLSTICKSANDWICH'] = ta.CDLSTICKSANDWICH(open_p, high_p, low_p, close_p)
  
  #CDLTAKURI - Takuri (Dragonfly Doji with very long lower shadow)
  e_f['CDLTAKURI'] = ta.CDLTAKURI(open_p, high_p, low_p, close_p)
  
  #CDLTASUKIGAP - Tasuki Gap
  e_f['CDLTASUKIGAP'] = ta.CDLTASUKIGAP(open_p, high_p, low_p, close_p)
  
  #CDLTHRUSTING - Thrusting Pattern
  e_f['CDLTHRUSTING'] = ta.CDLTHRUSTING(open_p, high_p, low_p, close_p)
  
  #CDLTRISTAR - Tristar Pattern
  e_f['CDLTRISTAR'] = ta.CDLTRISTAR(open_p, high_p, low_p, close_p)
  
  #CDLUNIQUE3RIVER - Unique 3 River
  e_f['CDLUNIQUE3RIVER'] = ta.CDLUNIQUE3RIVER(open_p, high_p, low_p, close_p)
  
  #CDLUPSIDEGAP2CROWS - Upside Gap Two Crows
  e_f['CDLUPSIDEGAP2CROWS'] = ta.CDLUPSIDEGAP2CROWS(open_p, high_p, low_p, close_p)
  
  #CDLXSIDEGAP3METHODS - Upside/Downside Gap Three Methods
  e_f['CDLXSIDEGAP3METHODS'] = ta.CDLXSIDEGAP3METHODS(open_p, high_p, low_p, close_p)
  
  #- Statistic Functions
  
  #BETA - Beta
  e_f['BETA'] = ta.BETA(high_p, low_p, timeperiod=5)
  
  #CORREL - Pearson's Correlation Coefficient (r)
  e_f['CORREL'] = ta.CORREL(high_p, low_p, timeperiod=30)
  
  #LINEARREG - Linear Regression
  e_f['LINEARREG'] = ta.LINEARREG(close_p, timeperiod=14)
  
  #LINEARREG_ANGLE - Linear Regression Angle
  e_f['LINEARREG_ANGLE'] = ta.LINEARREG_ANGLE(close_p, timeperiod=14)
  
  #LINEARREG_INTERCEPT - Linear Regression Intercept
  e_f['LINEARREG_INTERCEPT'] = ta.LINEARREG_INTERCEPT(close_p, timeperiod=14)
  
  #LINEARREG_SLOPE - Linear Regression Slope
  e_f['LINEARREG_SLOPE'] = ta.LINEARREG_SLOPE(close_p, timeperiod=14)
  
  #STDDEV - Standard Deviation
  e_f['STDDEV'] = ta.STDDEV(close_p, timeperiod=5, nbdev=1)
  
  #TSF - Time Series Frecast
  e_f['TSF'] = ta.TSF(close_p, timeperiod=14)
  
  #VAR - Variance
  e_f['VAR'] = ta.VAR(close_p, timeperiod=5, nbdev=1)
  
  
  ###########- Math Transform Functions
  
  #ACOS - Vector Trigonometric ACos
  e_f['ACOS'] = ta.ACOS(close_p)
  
  #ASIN - Vector Trigonometric ASin
  e_f['ASIN'] = ta.ASIN(close_p)
  
  #ATAN - Vector Trigonometric ATan
  e_f['ATAN'] = ta.ATAN(close_p)
  
  #CEIL - Vector Ceil
  e_f['CEIL'] = ta.CEIL(close_p)
  
  #COS - Vector Trigonometric Cos
  e_f['COS'] = ta.COS(close_p)
  
  #COSH - Vector Trigonometric Cosh
  e_f['COSH'] = ta.COSH(close_p)
  
  #EXP - Vector Arithmetic Exp
  e_f['EXP'] = ta.EXP(close_p)
  
  #FLOOR - Vector Floor
  e_f['FLOOR'] = ta.FLOOR(close_p)
  
  #LN - Vector Log Natural
  e_f['LN'] = ta.LN(close_p)
  
  #LOG10 - Vector Log10
  e_f['LOG10'] = ta.LOG10(close_p)
  
  #SIN - Vector Trigonometric Sin
  e_f['SIN'] = ta.SIN(close_p)
  
  #SINH - Vector Trigonometric Sinh
  e_f['SINH'] = ta.SINH(close_p)
  
  #SQRT - Vector Square Root
  e_f['SQRT'] = ta.SQRT(close_p)
  
  #TAN - Vector Trigonometric Tan
  e_f['TAN'] = ta.TAN(close_p)
  
  #TANH - Vector Trigonometric Tanh
  e_f['TANH'] = ta.TANH(close_p)
  
  #######- Math Operator Functions
  
  #ADD - Vector Arithmetic Add
  e_f['ADD'] = ta.ADD(high_p, low_p)
  
  #DIV - Vector Arithmetic Div
  e_f['DIV'] = ta.DIV(high_p, low_p)
  
  #MAX - high_pest value over a specified period
  e_f['MAX'] = ta.MAX(close_p, timeperiod=30)
  
  #MAXINDEX - Index of high_pest value over a specified period
  e_f['MAXINDEX'] = ta.MAXINDEX(close_p, timeperiod=30)
  
  #MIN - Lowest value over a specified period
  e_f['MIN'] = ta.MIN(close_p, timeperiod=30)
  
  #MININDEX - Index of lowest value over a specified period
  e_f['MININDEX'] = ta.MININDEX(close_p, timeperiod=30)
  
  #MINMAX - Lowest and high_pest values over a specified period
  min, max = ta.MINMAX(close_p, timeperiod=30)
  
  #MINMAXINDEX - Indexes of lowest and high_pest values over a specified period
  minidx, maxidx = ta.MINMAXINDEX(close_p, timeperiod=30)
  
  #MULT - Vector Arithmetic Mult
  e_f['MULT'] = ta.MULT(high_p, low_p)
  
  #SUB - Vector Arithmetic Substraction
  e_f['SUB'] = ta.SUB(high_p, low_p)
  
  #SUM - Summation
  e_f['SUM'] = ta.SUM(close_p, timeperiod=30)
  return(e_f)

In [58]:
raw_data

,일자,시간,시가,고가,저가,종가,거래량,단순 5,Unnamed: 8
0,2019/10/30,13:44:00,275.95,276.00,275.90,276.00,430,,NaN
1,2019/10/30,13:45:00,276.00,276.00,275.90,275.95,374,,NaN
2,2019/10/30,13:46:00,276.00,276.00,275.85,275.85,221,,NaN
3,2019/10/30,13:47:00,275.85,275.85,275.85,275.85,326,,NaN
4,2019/10/30,13:48:00,275.85,275.90,275.85,275.85,29,276,NaN
...,...,...,...,...,...,...,...,...,...
65530,2020/07/01,13:06:00,282.40,282.40,282.25,282.25,417,283.6,NaN
65531,2020/07/01,13:07:00,282.25,282.35,282.25,282.35,118,245.2,NaN
65532,2020/07/01,13:08:00,282.35,282.35,282.15,282.25,483,284.4,NaN
65533,2020/07/01,13:09:00,282.25,282.30,282.20,282.20,191,256.4,NaN
65534,2020/07/01,13:10:00,282.25,282.30,282.25,282.30,78,257.4,NaN

In [75]:
tech = data_make_function(raw_data['시가'], raw_data['고가'],raw_data['저가'],raw_data['종가'],raw_data['거래량'])
tech.to_csv('./tech.csv')

In [60]:
raw_data.shape
tech.shape

(65535, 9)

(65535, 159)

In [61]:
raw_data.head(100)

,일자,시간,시가,고가,저가,종가,거래량,단순 5,Unnamed: 8
0,2019/10/30,13:44:00,275.95,276.00,275.90,276.00,430,,NaN
1,2019/10/30,13:45:00,276.00,276.00,275.90,275.95,374,,NaN
2,2019/10/30,13:46:00,276.00,276.00,275.85,275.85,221,,NaN
3,2019/10/30,13:47:00,275.85,275.85,275.85,275.85,326,,NaN
4,2019/10/30,13:48:00,275.85,275.90,275.85,275.85,29,276,NaN
...,...,...,...,...,...,...,...,...,...
95,2019/10/30,15:19:00,275.65,275.75,275.60,275.70,738,536.4,NaN
96,2019/10/30,15:20:00,275.70,275.75,275.65,275.75,379,539.8,NaN
97,2019/10/30,15:21:00,275.70,275.75,275.65,275.70,856,651,NaN
98,2019/10/30,15:22:00,275.70,275.70,275.65,275.70,431,728,NaN
99,2019/10/30,15:23:00,275.75,275.75,275.70,275.70,44,489.6,NaN

In [62]:
raw_data['datetime'] = raw_data['일자'] + ' ' + raw_data['시간']
raw_data['datetime']

0        2019/10/30 13:44:00
1        2019/10/30 13:45:00
2        2019/10/30 13:46:00
3        2019/10/30 13:47:00
4        2019/10/30 13:48:00
                ...
65530    2020/07/01 13:06:00
65531    2020/07/01 13:07:00
65532    2020/07/01 13:08:00
65533    2020/07/01 13:09:00
65534    2020/07/01 13:10:00
Name: datetime, Length: 65535, dtype: object

In [63]:
raw_data['datetime'] = pd.to_datetime(raw_data['datetime'], format='%Y/%m/%d')
raw_data['datetime']

0       2019-10-30 13:44:00
1       2019-10-30 13:45:00
2       2019-10-30 13:46:00
3       2019-10-30 13:47:00
4       2019-10-30 13:48:00
                ...
65530   2020-07-01 13:06:00
65531   2020-07-01 13:07:00
65532   2020-07-01 13:08:00
65533   2020-07-01 13:09:00
65534   2020-07-01 13:10:00
Name: datetime, Length: 65535, dtype: datetime64[ns]

In [64]:
raw_data.dtypes

일자                    object
시간                    object
시가                   float64
고가                   float64
저가                   float64
종가                   float64
거래량                    int64
단순 5                  object
Unnamed: 8           float64
datetime      datetime64[ns]
dtype: object

In [65]:
data = raw_data[['datetime', '종가']]
data.columns = ['datetime', 'close']
data

                 datetime   close
0     2019-10-30 13:44:00  276.00
1     2019-10-30 13:45:00  275.95
2     2019-10-30 13:46:00  275.85
3     2019-10-30 13:47:00  275.85
4     2019-10-30 13:48:00  275.85
...                   ...     ...
65530 2020-07-01 13:06:00  282.25
65531 2020-07-01 13:07:00  282.35
65532 2020-07-01 13:08:00  282.25
65533 2020-07-01 13:09:00  282.20
65534 2020-07-01 13:10:00  282.30

[65535 rows x 2 columns]

In [66]:
data = pd.concat([data, tech], axis = 1)
#data.set_index('datetime', inplace = True)
data
original_col = data.columns.to_list()

,datetime,close,BBANDS_upperband,BBANDS_middleband,BBANDS_lowerband,DEMA,EMA,HT_TRENDLINE,KAMA,MA,...,TANH,ADD,DIV,MAX,MAXINDEX,MIN,MININDEX,MULT,SUB,SUM
0,2019-10-30 13:44:00,276.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,551.90,1.000362,NaN,0,NaN,0,76148.4000,0.10,NaN
1,2019-10-30 13:45:00,275.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,551.90,1.000362,NaN,0,NaN,0,76148.4000,0.10,NaN
2,2019-10-30 13:46:00,275.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,551.85,1.000544,NaN,0,NaN,0,76134.6000,0.15,NaN
3,2019-10-30 13:47:00,275.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,551.70,1.000000,NaN,0,NaN,0,76093.2225,0.00,NaN
4,2019-10-30 13:48:00,275.85,276.026491,275.90,275.773509,NaN,NaN,NaN,NaN,NaN,...,1.0,551.75,1.000181,NaN,0,NaN,0,76107.0150,0.05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,2020-07-01 13:06:00,282.25,282.505647,282.37,282.234353,282.354359,282.268595,282.297462,282.120367,282.278333,...,1.0,564.65,1.000531,282.45,65528,282.0,65501,79707.4000,0.15,8468.35
65531,2020-07-01 13:07:00,282.35,282.505647,282.37,282.234353,282.358991,282.273847,282.307521,282.127207,282.290000,...,1.0,564.60,1.000354,282.45,65528,282.1,65502,79693.2875,0.10,8468.70
65532,2020-07-01 13:08:00,282.25,282.500000,282.34,282.180000,282.350520,282.272309,282.310707,282.128716,282.295000,...,1.0,564.50,1.000709,282.45,65528,282.1,65503,79665.0525,0.20,8468.85
65533,2020-07-01 13:09:00,282.20,282.436969,282.29,282.143031,282.336445,282.267643,282.308717,282.129354,282.298333,...,1.0,564.50,1.000354,282.45,65528,282.2,65504,79665.0600,0.10,8468.95
65534,2020-07-01 13:10:00,282.30,282.371981,282.27,282.168019,282.336047,282.269731,282.305846,282.130882,282.301667,...,1.0,564.55,1.000177,282.45,65528,282.2,65506,79679.1750,0.05,8469.05

In [74]:
"""
    해야 되는 것.
    1. (1~20)분 후의 가격 ~ price_1m
    2. (1~20)분 후의 로그수익률 ~ lgret_1m
    3. (1~20)분 후의 절대수익률 ~ ret_1m
"""
for i in range(1, 21):
    num_label = str(i) + 'm'
    data['price_' + num_label] = data['close'] - data['close'].iloc[i:].reset_index(drop = True)
    data['ret_' + num_label] = (data['close'].iloc[i:].reset_index(drop = True) - data['close'])/data['close']
    data['logret_' + num_label] = np.log(data['close'].iloc[i:].reset_index(drop = True)/data['close'])
#data.to_csv('./data_with_all_y.csv')

'\n    해야 되는 것.\n    1. (1~20)분 후의 가격 ~ price_1m\n    2. (1~20)분 후의 로그수익률 ~ lgret_1m\n    3. (1~20)분 후의 절대수익률 ~ ret_1m\n'

In [72]:
data = pd.read_csv('./data_with_all_y.csv')
def extract_data(method, period): # method : ('price', 'ret', 'logret'), period = 1~20
    label = method + '_' + str(period) + 'm'
    cols = original_col.copy()
    cols.append(label)
    _data = data[cols]
    _data.set_index('datetime', inplace = True, drop = True)
    return _data

In [73]:
extract_data('price', 1)

,close,BBANDS_upperband,BBANDS_middleband,BBANDS_lowerband,DEMA,EMA,HT_TRENDLINE,KAMA,MA,MIDPOINT,...,ADD,DIV,MAX,MAXINDEX,MIN,MININDEX,MULT,SUB,SUM,price_1m
datetime,,,,,,,,,,,,,,,,,,,,,
2019-10-30 13:44:00,276.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,551.90,1.000362,NaN,0,NaN,0,76148.4000,0.10,NaN,0.05
2019-10-30 13:45:00,275.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,551.90,1.000362,NaN,0,NaN,0,76148.4000,0.10,NaN,0.10
2019-10-30 13:46:00,275.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,551.85,1.000544,NaN,0,NaN,0,76134.6000,0.15,NaN,0.00
2019-10-30 13:47:00,275.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,551.70,1.000000,NaN,0,NaN,0,76093.2225,0.00,NaN,0.00
2019-10-30 13:48:00,275.85,276.026491,275.90,275.773509,NaN,NaN,NaN,NaN,NaN,NaN,...,551.75,1.000181,NaN,0,NaN,0,76107.0150,0.05,NaN,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-01 13:06:00,282.25,282.505647,282.37,282.234353,282.354359,282.268595,282.297462,282.120367,282.278333,282.325,...,564.65,1.000531,282.45,65528,282.0,65501,79707.4000,0.15,8468.35,-0.10
2020-07-01 13:07:00,282.35,282.505647,282.37,282.234353,282.358991,282.273847,282.307521,282.127207,282.290000,282.325,...,564.60,1.000354,282.45,65528,282.1,65502,79693.2875,0.10,8468.70,0.10
2020-07-01 13:08:00,282.25,282.500000,282.34,282.180000,282.350520,282.272309,282.310707,282.128716,282.295000,282.325,...,564.50,1.000709,282.45,65528,282.1,65503,79665.0525,0.20,8468.85,0.05
2020-07-01 13:09:00,282.20,282.436969,282.29,282.143031,282.336445,282.267643,282.308717,282.129354,282.298333,282.325,...,564.50,1.000354,282.45,65528,282.2,65504,79665.0600,0.10,8468.95,-0.10
2020-07-01 13:10:00,282.30,282.371981,282.27,282.168019,282.336047,282.269731,282.305846,282.130882,282.301667,282.325,...,564.55,1.000177,282.45,65528,282.2,65506,79679.1750,0.05,8469.05,NaN